# This file was generated by GoReleaser. DO NOT EDIT.
cask "gajevids" do
  desc "YAML-based FFmpeg video composition tool"
  homepage "https://github.com/gajeroll/gajevids"
  version "0.3.20"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gajevids"

  on_macos do
    on_intel do
      url "https://github.com/gajeroll/homebrew-gajevids/releases/download/v0.3.20/gajevids_0.3.20_darwin_amd64.tar.gz",
        verified: "github.com/gajeroll/homebrew-gajevids"
      sha256 "307529638952fccfa3ca612efba6f9db2814162f66bf6c38b2c7dc14e8dbf588"
    end
    on_arm do
      url "https://github.com/gajeroll/homebrew-gajevids/releases/download/v0.3.20/gajevids_0.3.20_darwin_arm64.tar.gz",
        verified: "github.com/gajeroll/homebrew-gajevids"
      sha256 "561aa3502451b9185d2113ced198ff582e94fda193712c3639e518131fe5e26f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/gajeroll/homebrew-gajevids/releases/download/v0.3.20/gajevids_0.3.20_linux_amd64.tar.gz",
        verified: "github.com/gajeroll/homebrew-gajevids"
      sha256 "cfe4a44745cf0ea8cde411e82e896ff6a4b2c465f19360c3d3932fe962e67e73"
    end
    on_arm do
      url "https://github.com/gajeroll/homebrew-gajevids/releases/download/v0.3.20/gajevids_0.3.20_linux_arm64.tar.gz",
        verified: "github.com/gajeroll/homebrew-gajevids"
      sha256 "0c1381af39c99cdcc5bc4a1af5a7a7431429742d30aa7d5090884bfa5c67ee4b"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status.zero?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/gajevids"]
    end
  end

  caveats do
    "After installing, you may need to remove Gatekeeper quarantine attributes:"
    "  sudo xattr -dr com.apple.quarantine /opt/homebrew/Caskroom/gajevids/latest"
  end

  # No zap stanza required
end
