# This file was generated by GoReleaser. DO NOT EDIT.
cask "gajevids" do
  desc "YAML-based FFmpeg video composition tool"
  homepage "https://github.com/gajeroll/gajevids"
  version "0.3.21"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gajevids"

  on_macos do
    on_intel do
      url "https://github.com/gajeroll/homebrew-gajevids/releases/download/v0.3.21/gajevids_0.3.21_darwin_amd64.tar.gz",
        verified: "github.com/gajeroll/homebrew-gajevids"
      sha256 "6f10f9bf59a36a99bd38f09ad91e76fd63d7a1cc77a32911b337b93c9d14fbbf"
    end
    on_arm do
      url "https://github.com/gajeroll/homebrew-gajevids/releases/download/v0.3.21/gajevids_0.3.21_darwin_arm64.tar.gz",
        verified: "github.com/gajeroll/homebrew-gajevids"
      sha256 "7fb6ed50dd0e900f2530812490d4cbff13532a364d02d4071a3c40e08162510d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/gajeroll/homebrew-gajevids/releases/download/v0.3.21/gajevids_0.3.21_linux_amd64.tar.gz",
        verified: "github.com/gajeroll/homebrew-gajevids"
      sha256 "a1e9e311b7ce071b40602648679186987a52b1de3976b62801f2493f67419943"
    end
    on_arm do
      url "https://github.com/gajeroll/homebrew-gajevids/releases/download/v0.3.21/gajevids_0.3.21_linux_arm64.tar.gz",
        verified: "github.com/gajeroll/homebrew-gajevids"
      sha256 "69751bac5509c8a6f38fddb1df3157804d7b360433a3158d8f765819cddf3b62"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status.zero?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/gajevids"]
    end
  end

  caveats do
    "After installing, you may need to remove Gatekeeper quarantine attributes:"
    "  sudo xattr -dr com.apple.quarantine /opt/homebrew/Caskroom/gajevids/latest"
  end

  # No zap stanza required
end
