# This file was generated by GoReleaser. DO NOT EDIT.
cask "gajevids" do
  desc "YAML-based FFmpeg video composition tool"
  homepage "https://github.com/gajeroll/gajevids"
  version "0.3.26"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gajevids"

  on_macos do
    on_intel do
      url "https://github.com/gajeroll/homebrew-gajevids/releases/download/v0.3.26/gajevids_0.3.26_darwin_amd64.tar.gz",
        verified: "github.com/gajeroll/homebrew-gajevids"
      sha256 "8c5d3841befb54e38068149adbfa9c30f32e6f5e9c253151723f2e04a46308b2"
    end
    on_arm do
      url "https://github.com/gajeroll/homebrew-gajevids/releases/download/v0.3.26/gajevids_0.3.26_darwin_arm64.tar.gz",
        verified: "github.com/gajeroll/homebrew-gajevids"
      sha256 "31a03500920f426581037777cbf3f93d35c87ca5cdb6ebd93584886539d5c7e7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/gajeroll/homebrew-gajevids/releases/download/v0.3.26/gajevids_0.3.26_linux_amd64.tar.gz",
        verified: "github.com/gajeroll/homebrew-gajevids"
      sha256 "115461a7828f0caa31f55ba98aac386da458e5a32b879fed53a986b2c5e39813"
    end
    on_arm do
      url "https://github.com/gajeroll/homebrew-gajevids/releases/download/v0.3.26/gajevids_0.3.26_linux_arm64.tar.gz",
        verified: "github.com/gajeroll/homebrew-gajevids"
      sha256 "9a2772262de6613b90127d963c5205abe97bbe4176721101d80d2e415bf91424"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status.zero?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/gajevids"]
    end
  end

  caveats do
    "After installing, you may need to remove Gatekeeper quarantine attributes:"
    "  sudo xattr -dr com.apple.quarantine /opt/homebrew/Caskroom/gajevids/latest"
  end

  # No zap stanza required
end
